# Generated by Django 4.0.5 on 2022-06-20 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Room_Application_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_number', models.CharField(max_length=5)),
                ('Amount_paid_in_Naira', models.DecimalField(decimal_places=2, max_digits=10000000)),
                ('Occupant_Name', models.CharField(max_length=1000)),
                ('Occupant_email', models.EmailField(max_length=254)),
                ('Occupant_occupation', models.CharField(max_length=10000)),
                ('Number_of_night', models.IntegerField()),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
